- name: Instalar JBoss EAP
  hosts: local
  become: true

  vars:
    download_file: "https://access.redhat.com/cspdownload/dd5336f04b26999f84b9f634b84abfef/64571604/JBEAP-7.4.0/jboss-eap-7.4.0.zip"
    make_download: "no"
    make_copy: "yes"
    dir_origem_pack: "/opt/ansible/playbook_jboss/"
    version_file: "jboss-eap-7.4.0.zip"
    version_eap: "jboss-eap-7.4"
    jboss_dir: "/opt/jboss/"
    jboss_user: "jbossadmin"
    jboss_password: "jbossadmin"
    host_name_server: "master"
    host_management_ip: "localhost"
    host_public_ip: "localhost"
    host_domain_controller: "<local/>"
    dir_template: "/opt/ansible/playbook_jboss/"

  tasks:
    - name: Criar diretório /opt/jboss
      file:
        path: "{{ jboss_dir }}"
        state: directory

    - name: Baixar o arquivo JBoss EAP "{{ version_file }}"
      get_url:
        url: "{{ download_file }}"
        dest: "{{ jboss_dir }}{{ version_file }}"
      when: make_download == "yes"

    - name: Copiar pacote Jboss EAP "{{ version_file }}" 
      copy:
        src: "{{ dir_origem_pack }}{{ version_file }}"
        dest: "{{ jboss_dir }}{{ version_file }}"
        remote_src: yes
      when: make_copy == "yes"

    - name: Extrair o arquivo JBoss EAP
      unarchive:
        src: "{{ jboss_dir }}{{ version_file }}"
        dest: "{{ jboss_dir }}"
        remote_src: yes
        #copy: no

    - name: Remover o arquivo JBoss EAP zip
      file:
        path: "{{ jboss_dir }}{{ version_file }}"
        state: absent

    - name: Criar user adm JBoss
      shell: "{{ jboss_dir }}{{ version_eap }}/bin/add-user.sh -u {{ jboss_user }} -p {{ jboss_password }} -g admin"
    
    - name: Copia template host.xml
      template:
        src: "{{ dir_template }}/host.xml.j2"
        dest: "{{ jboss_dir }}{{ version_eap }}//domain/configuration/host.xml"

    - name: Copia template domain.xml
      template:
        src: "{{ dir_template }}/domain.xml.j2"       
        dest: "{{ jboss_dir }}{{ version_eap }}//domain/configuration/domain.xml"


    - name: Start Domain Controller
      shell: |
        nohup "{{ jboss_dir }}{{ version_eap }}"/bin/domain.sh &
